project:
  title: "ivanstepanovftw"
  type: website
  output-dir: docs

format:
  html:
    toc: true
#    html-math-method: mathml
    html-math-method: webtex
#    html-math-method: gladtex
    link-external-icon: true
    link-external-newwindow: true
