title: My Site
theme: jekyll-theme-cayman
markdown: kramdown

kramdown:
  input: GFM
#  math_engine: katex
#  syntax_highlighter: rouge
  math_engine: mathjax
  math_engine_opts:
    output: svg
    preview: false

plugins:
  - jekyll-header-id
  - jekyll-inline-svg
  - jekyll-target-blank

# Настройки для jekyll-target-blank (все внешние ссылки)
target-blank:
  enabled: true
  rel: ["noopener"]
  exclude: ["example.com"]  # если нужно исключить домены (опционально)

# inline-svg можно использовать как {% inline_svg path/to.svg %}
inline_svg:
  optimize: true

relative_links:
  enabled: true
  collections: true

include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
